[zen] Gtorres/zen badlint (#772)
eslint

diff --git a/.zen.yaml b/.zen.yaml
--- a/.zen.yaml
+++ b/.zen.yaml
@@ -43,8 +43,25 @@ script:
   cp settings.xml /home/mvn-user/.m2/settings.xml
   chown -R mvn-user /home/mvn-user/.m2
   chown -R mvn-user $(pwd)
-  sudo -iu mvn-user bash -c "cd $(pwd);mvn pre-clean -Peslint && mvn clean deploy $MAVEN_ARGS -Dmaven.repo.local=$(pwd)/.m2/repository -DaltDeploymentRepository=zen::default::file://$(pwd)/$LOCAL_DEPLOY_DIR -Dnode.download.root.url=http://localhost/node/ -Dchromedriver.download.root.url=http://localhost/chromedriver -Dnpm.download.root.url=http://localhost/npm/" || export status=$? || true
-  sudo -iu mvn-user bash -c "cd $(pwd);set -x;export LANG=\"en_US.UTF-8\";mvn post-integration-test $MAVEN_ARGS -Dmaven.repo.local=$(pwd)/.m2/repository -DaltDeploymentRepository=zen::default::file://$(pwd)/$LOCAL_DEPLOY_DIR -Dnode.download.root.url=http://localhost/node/ -Dchromedriver.download.root.url=http://localhost/chromedriver -Dnpm.download.root.url=http://localhost/npm/ -Pdesktop -DskipJsDoc -DskipComponentCompile -DskipUnitTests -DrunIntTests -Dwebdriver.browser.type=GOOGLECHROME -Dwebdriver.chrome.nosandbox=true -Dwebdriver.reusebrowser=true -Dwebdriver.timeout=90 -Dwebdriver.timeout.getdriver=30 -DtestThreadCount=3 -DtestNameContains=jsmock" || export status=$? || true
+  sudo -iu mvn-user bash -c "\
+    cd $(pwd);
+    mvn pre-clean -Peslint || {
+      status=$?;
+      [ ! -s aura-impl/target/eslint-output ] || {
+        echo '[ERROR] ------------------------------------------------------------------------';
+        echo '[ERROR] Failed with the following eslint errors:';
+        echo '[ERROR]';
+        cat aura-impl/target/eslint-output | sed 's/^/[ERROR] /';
+        echo '[ERROR]';
+        echo '[ERROR] ------------------------------------------------------------------------';
+      };
+      exit $status;
+    };
+    mvn clean deploy $MAVEN_ARGS -Dmaven.repo.local=$(pwd)/.m2/repository -DaltDeploymentRepository=zen::default::file://$(pwd)/$LOCAL_DEPLOY_DIR -Dnode.download.root.url=http://localhost/node/ -Dchromedriver.download.root.url=http://localhost/chromedriver -Dnpm.download.root.url=http://localhost/npm/ || exit $?;
+    set -x;
+    export LANG=\"en_US.UTF-8\";
+    mvn post-integration-test $MAVEN_ARGS -Dmaven.repo.local=$(pwd)/.m2/repository -DaltDeploymentRepository=zen::default::file://$(pwd)/$LOCAL_DEPLOY_DIR -Dnode.download.root.url=http://localhost/node/ -Dchromedriver.download.root.url=http://localhost/chromedriver -Dnpm.download.root.url=http://localhost/npm/ -Pdesktop -DskipJsDoc -DskipComponentCompile -DskipUnitTests -DrunIntTests -Dwebdriver.browser.type=GOOGLECHROME -Dwebdriver.chrome.nosandbox=true -Dwebdriver.reusebrowser=true -Dwebdriver.timeout=90 -Dwebdriver.timeout.getdriver=30 -DtestThreadCount=3 -DtestNameContains=jsmock || true"
+  status=$?
   chown -R $ORIG_UID:$ORIG_UID $(pwd)
   exit ${status:-0}
 # It is currently required that there be an empty line following the script: section
